"""Auto

Revision ID: 04eb65c85acd
Revises: bd937a7186c1
Create Date: 2025-07-08 19:15:30.647178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_storages


# revision identifiers, used by Alembic.
revision: str = '04eb65c85acd'
down_revision: Union[str, Sequence[str], None] = 'bd937a7186c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


storage = fastapi_storages.FileSystemStorage(path="/nfs/dvr/plates")


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('file', fastapi_storages.integrations.sqlalchemy.FileType(storage=storage), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'file')
    # ### end Alembic commands ###
