"""Auto

Revision ID: 103d193e1f8d
Revises: 887527be877d
Create Date: 2025-07-08 21:38:46.212322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '103d193e1f8d'
down_revision: Union[str, Sequence[str], None] = '887527be877d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('titles', sa.Column('code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('titles', 'code')
    # ### end Alembic commands ###
