"""Auto

Revision ID: 54220127a862
Revises: 740f1e94dfe9
Create Date: 2025-07-08 18:46:14.297561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54220127a862'
down_revision: Union[str, Sequence[str], None] = '740f1e94dfe9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('name', sa.String(), nullable=False))
    op.add_column('authors', sa.Column('short', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('authors', 'short')
    op.drop_column('authors', 'name')
    # ### end Alembic commands ###
