"""Auto

Revision ID: 887527be877d
Revises: a5ed06e6cf8d
Create Date: 2025-07-08 21:07:32.935311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '887527be877d'
down_revision: Union[str, Sequence[str], None] = 'a5ed06e6cf8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


import fastapi_storages
storage = fastapi_storages.FileSystemStorage(path="/nfs/dvr/plates")


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('titles', sa.Column('year', sa.Integer(), nullable=True))
    op.add_column('titles', sa.Column('pages', sa.Integer(), nullable=True))
    op.add_column('titles', sa.Column('logo', fastapi_storages.integrations.sqlalchemy.ImageType(storage=storage), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('titles', 'logo')
    op.drop_column('titles', 'pages')
    op.drop_column('titles', 'year')
    # ### end Alembic commands ###
