"""Auto

Revision ID: a5ed06e6cf8d
Revises: 04eb65c85acd
Create Date: 2025-07-08 20:32:48.737583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5ed06e6cf8d'
down_revision: Union[str, Sequence[str], None] = '04eb65c85acd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'url')
    # ### end Alembic commands ###
