"""Auto

Revision ID: bd937a7186c1
Revises: 54220127a862
Create Date: 2025-07-08 18:53:54.710779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd937a7186c1'
down_revision: Union[str, Sequence[str], None] = '54220127a862'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('titles', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('titles', 'name')
    # ### end Alembic commands ###
